version: '3.2'

services:

  api:
    ports:
      - "8001:8000"
    build:
      context: .
      dockerfile: Dockerfile.API.dev
    volumes:
      - type: volume
        source: ../src
        target: /root/src
